name: Release New Version
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v3

      - name: Set Version
        run: |
          sed -i 's/debug-build/${{ github.event.release.tag_name }}/g' gradle.properties
          sed -i 's/debug-build/${{ github.event.release.tag_name }}/g' fabric/src/main/resources/fabric.mod.json
          sed -i 's/0.debug-build/${{ github.event.release.tag_name }}/g' forge/src/main/resources/META_INF/mods.toml

      - name: Build
        run: ./gradlew build

      - name: Publish Fabric
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: CvQCitpB
          modrinth-featured: true
          modrinth-unfeature-mode: version-subset
          version: ${{ github.event.release.tag_name }}-fabric
          files: ${{ github.workspace }}/fabric/build/libs/EasyEula-${{ github.event.release.tag_name }}.zip
          java: 17
          game-versions: |
            [1.20,1.20.4)
            [1.19,1.19.4)
            [1.18,1.18.2)
            [1.17,1.17.1)
            [1.16,1.16.5)
            [1.15,1.15.2)
          loaders: |
            fabric
            quilt

      - name: Publish Forge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: CvQCitpB
          modrinth-featured: true
          modrinth-unfeature-mode: version-subset
          version: ${{ github.event.release.tag_name }}-forge
          files: ${{ github.workspace }}/forge/build/libs/EasyEula-${{ github.event.release.tag_name }}.zip
          java: 17
          game-versions: |
            [1.20,1.20.4)
            [1.19,1.19.4)
            [1.18,1.18.2)
            [1.17,1.17.1)
            [1.16,1.16.5)
            [1.15,1.15.2)
          loaders: |
            forge