name: Release New Version
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set Fabric Version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: src/main/resources/fabric.mod.json
          field: version
          value: ${{ github.event.release.tag_name }}

      - name: Set Forge Version
        uses: ciiiii/toml-editor@1.0.0
        with:
          file: src/main/resources/META_INF/mods.toml
          key: mods.version
          value: ${{ github.event.release.tag_name }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename File
        run: mv ${{ github.workspace }}/build/libs/EasyEula-*.jar ${{ github.workspace }}/EasyEula-${{ github.event.release.tag_name }}.jar;

      - name: Publish Release
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-featured: true
          files: ${{ github.workspace }}/*.jar
          java: 17
          game-versions: |
            1.20.4
            1.20.3
            1.20.2
            1.20.1
            1.20
            1.19.4
            1.19.3
            1.19.2
            1.19.1
            1.19
            1.18.2
            1.18.1
            1.18
            1.17.1
            1.17
            1.16.5
            1.15.2
            1.15.1
            1.15
            1.14.4
            1.14.3
            1.14.2
            1.14.1
            1.14
          loaders: |
            fabric
            quilt
            forge